export const AuditEntity = {
  USER: "User",
  TRIP: "Trip",
  NOTIFICATION: "Notification",
} as const;

export const AuditAction = {
  USER_CREATED: "USER_CREATED",
  USER_LOGIN: "USER_LOGIN",
  ADMIN_LOGIN: "ADMIN_LOGIN",
  USER_TOKEN_REFRESHED: "USER_TOKEN_REFRESHED",
  USER_PASSWORD_CHANGED: "USER_PASSWORD_CHANGED",
  TRIP_CREATED: "TRIP_CREATED",
  TRIP_UPDATED: "TRIP_UPDATED",
  TRIP_RESUBMITTED: "TRIP_RESUBMITTED",
  TRIP_DELETED: "TRIP_DELETED",
  TRIP_APPROVED: "TRIP_APPROVED",
  TRIP_REJECTED: "TRIP_REJECTED",
  NOTIFICATION_READ: "NOTIFICATION_READ",
  NOTIFICATION_DELETED: "NOTIFICATION_DELETED",
  USER_TEMPORARY_PASSWORD_SET: "USER_TEMPORARY_PASSWORD_SET",
  USER_LOGOUT: "USER_LOGOUT",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_ACTIVATED: "USER_ACTIVATED",
} as const;
