export const AuditEntity = {
  USER: 'User',
  TRIP: 'Trip',
  NOTIFICATION: 'Notification',
} as const;

export const AuditAction = {
  USER_CREATED: 'USER_CREATED',
  TRIP_CREATED: 'TRIP_CREATED',
  TRIP_UPDATED: 'TRIP_UPDATED',
  TRIP_RESUBMITTED: 'TRIP_RESUBMITTED',
  TRIP_DELETED: 'TRIP_DELETED',
  TRIP_APPROVED: 'TRIP_APPROVED',
  TRIP_REJECTED: 'TRIP_REJECTED',
  NOTIFICATION_READ: 'NOTIFICATION_READ',
  USER_TEMPORARY_PASSWORD_SET: 'USER_TEMPORARY_PASSWORD_SET',
} as const;
